export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# Allow running Hadoop services as cloudera user
export HDFS_NAMENODE_USER=cloudera
export HDFS_DATANODE_USER=cloudera
export HDFS_SECONDARYNAMENODE_USER=cloudera
export YARN_RESOURCEMANAGER_USER=cloudera
export YARN_NODEMANAGER_USER=cloudera

export HADOOP_CLIENT_OPTS="-Xmx${HADOOP_HEAP:-128m} $HADOOP_CLIENT_OPTS"
export HADOOP_NAMENODE_OPTS="-Xmx${HADOOP_HEAP:-256m} $HADOOP_NAMENODE_OPTS"
export HADOOP_DATANODE_OPTS="-Xmx${HADOOP_HEAP:-256m} $HADOOP_DATANODE_OPTS"
export HADOOP_RESOURCEMANAGER_OPTS="-Xmx${HADOOP_HEAP:-256m} $HADOOP_RESOURCEMANAGER_OPTS"
export HADOOP_NODEMANAGER_OPTS="-Xmx${HADOOP_HEAP:-256m} $HADOOP_NODEMANAGER_OPTS"
